version: "3.0"
services:
    app:
        build:
            args:
                - user=kanelli
                - uid=1000
            context: ./
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        ports:
            - "9000:9000"
        env_file:
            -   .env
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network
        depends_on:
            - mysql
            - redis
        command: >-
            sh -c " rm -rf vendor ;\
            composer install --ignore-platform-reqs ;\
            php artisan key:generate ;\
            php artisan migrate ";
    mysql:
     image: mysql:8.0
     container_name: mysql
     restart: unless-stopped
     ports:
         - "3306:3306"
     environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: laravel_study
        MYSQL_USER: test
        MYSQL_PASSWORD: test
     networks:
        - app-network

    nginx:
        image: nginx:1.21
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d
        networks:
            - app-network

    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - "6380:6380"
        environment:
            - TZ=Asia/Shanghai
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
