version: "3.0"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            -   .env
        container_name: app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "9000:9000"
        networks:
            - app-network
        depends_on:
            - mysql
            - redis
#        command: >-
#            sh -c "composer install --ignore-platform-reqs && php artisan migrate";
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_study
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        networks:
            - app-network

    nginx:
        image: nginx:1.21
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./conf/nginx:/etc/nginx/conf.d
        networks:
            - app-network
        depends_on:
            - app
        links:
            - app
#        command: nginx -g "daemon off;"

    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        environment:
            - TZ=Asia/Shanghai
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
